spring.application.name=data-aggregator

# Source PostgreSQL Database Configuration
source.datasource.url=jdbc:postgresql://YOUR_SOURCE_DB_HOST:PORT/YOUR_SOURCE_DB_NAME
source.datasource.username=YOUR_SOURCE_USERNAME
source.datasource.password=YOUR_SOURCE_PASSWORD
source.jpa.hibernate.ddl-auto=update
source.jpa.show-sql=true
source.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Target PostgreSQL Database Configuration
target.datasource.url=jdbc:postgresql://YOUR_TARGET_DB_HOST:PORT/YOUR_TARGET_DB_NAME
target.datasource.username=YOUR_TARGET_USERNAME
target.datasource.password=YOUR_TARGET_PASSWORD
# Hibernate properties for the target datasource (can be different from source)
target.jpa.hibernate.ddl-auto=update
target.jpa.show-sql=true
target.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
