spring.application.name=data-aggregator

# Source PostgreSQL Database Configuration (for local Docker instance)
# Example docker run: docker run --name some-postgres -e POSTGRES_PASSWORD=password -e POSTGRES_USER=user -e POSTGRES_DB=sample_source_db -p 5432:5432 -d postgres
source.datasource.url=jdbc:postgresql://localhost:5432/sample_source_db
source.datasource.username=user
source.datasource.password=password
source.jpa.hibernate.ddl-auto=update
source.jpa.show-sql=true
source.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Target H2 In-Memory Database Configuration
target.datasource.url=jdbc:h2:mem:targetdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
target.datasource.driverClassName=org.h2.Driver
target.datasource.username=sa
target.datasource.password=password
target.jpa.hibernate.ddl-auto=update
target.jpa.show-sql=true
target.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
