package com.example.dataaggregator.model.source;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import lombok.Data; // If Lombok is used

@Entity
@Data // Lombok annotation for getters, setters, toString, etc.
public class SourceData {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;
    private String value; // Example field

    // Constructors, getters, and setters will be generated by Lombok
    // If not using Lombok, you'll need to add them manually.
}
